parameters:
- name: suite_name
  type: string

- name: test_name
  type: string
  values:
  - cilium_linux
  - cilium_overlay_linux
  - cilium_overlay_dualstack
  - cilium_overlay_withhubble

- name: display_name
  type: string

- name: cluster_name
  type: string

- name: subscription 
  type: string

- name: depends_on
  type: object
  default: ''

- name: template_parameters
  type: object

jobs:
- job: run_e2e_${{ parameters.test_name }}
  displayName: ${{ parameters.display_name }} Test Suite - (${{ parameters.test_name }})
  dependsOn: ${{ parameters.depends_on }}
  timeoutInMinutes: 120
  pool: 
    type: linux
    isCustom: true
    name: $(BUILD_POOL_NAME_DEFAULT)
    demands:
    - agent.os -equals Linux
    - Role -equals $(CUSTOM_E2E_ROLE)
  steps:
  - bash: |
      set -e
      if [[ -n $OS ]]; then
        echo >&2 "'os_sku' is required param for 'cilium-e2e.jobs.yaml' template."
        exit 1
      fi      
    name: param_precheck
    displayName: Verify Template Parameters
    env:
      OS: ${{ parameters.template_parameters.os_sku }}

  - ${{ if eq(parameters.test_name, 'cilium_linux') }}:
    - template: tests/cilium.steps.yaml
      parameters:
        cluster_name: ${{ parameters.cluster_name }}
        subscription: ${{ parameters.subscription }}
  - ${{ elseif eq(parameters.test_name, 'cilium_overlay_linux') }}:
    - template: tests/cilium/cilium-overlay.steps.yaml
      parameters:
        cluster_name: ${{ parameters.cluster_name }}
        subscription: ${{ parameters.subscription }}
  - ${{ elseif eq(parameters.test_name, 'cilium_overlay_dualstack') }}:
    - template: tests/cilium/cilium-overlay-dualstack.steps.yaml
      parameters:
        cluster_name: ${{ parameters.cluster_name }}
        subscription: ${{ parameters.subscription }}
  - ${{ elseif eq(parameters.test_name, 'cilium_overlay_withhubble') }}:
    - template: tests/cilium/cilium-overlay-withhubble.steps.yaml
      parameters:
        cluster_name: ${{ parameters.cluster_name }}
        subscription: ${{ parameters.subscription }}
  - ${{ else }}:
    - error: Invalid test selection (${{ parameters.test_name }})

- job: cni_${{ parameters.test_name }}
  condition: and( not(canceled()), not(failed()) )
  displayName: CNI k8s E2E ${{ parameters.template_parameters.os_sku }}
  dependsOn: 
   - run_e2e_${{ parameters.test_name }}
   - ${{ each dep in parameters.depends_on }}:
     - ${{ dep }}
  pool: 
    type: windows
    isCustom: true
    name: $(BUILD_POOL_NAME_DEFAULT)
  steps:
  - template: ../../../cni/k8s-e2e/k8s-e2e.jobs.yaml
    parameters:
      subscription: ${{ parameters.subscription }}
      cluster_name: ${{ parameters.cluster_name }}
      os: ${{ parameters.template_parameters.os_sku }}
      cni: cilium
      is_dualstack: ${{ contains(parameters.test_name, 'dualstack') }}
      test_cases:
        - datapath
        - dns
        - portforward
        - service

- job: failurelogs_${{ parameters.test_name }}
  displayName: "Failure Logs"
  dependsOn:
    - cni_${{ parameters.test_name }}
  condition: failed()
  pool: 
    type: windows
    isCustom: true
    name: $(BUILD_POOL_NAME_DEFAULT)
  steps:
  - template: ../../../templates/log-template.yaml
    parameters:
      clusterName: ${{ parameters.cluster_name }}
      os: ${{ parameters.template_parameters.os_sku }}
      cni: cilium
      publish: false

  - task: PublishPipelineArtifact@1
    condition: always()
    name: drop_e2e_${{ parameters.suite_name }}_failurelogs_${{ parameters.test_name }}
    inputs:
      artifact: drop_e2e_${{ parameters.suite_name }}_failurelogs_${{ parameters.test_name }}
      targetPath: $(System.DefaultWorkingDirectory)/${{ parameters.cluster_name }}_failure_Attempt_#$(System.StageAttempt)
      publishLocation: pipeline
