parameters:
- name: os
  type: string
  values:
  - windows
  - linux

steps:
- ${{ if contains(parameters.os, 'windows') }}:
  - script: |
      set -e
      kubectl apply -f test/integration/manifests/load/privileged-daemonset-windows.yaml
      kubectl rollout status -n kube-system ds privileged-daemonset
  
      kubectl get pod -n kube-system -l app=privileged-daemonset,os=windows -owide
      pods=`kubectl get pod -n kube-system -l app=privileged-daemonset,os=windows --no-headers | awk '{print $1}'`
      for pod in $pods; do
        kubectl exec -i -n kube-system $pod -- powershell "Restart-Service kubeproxy"
        kubectl exec -i -n kube-system $pod -- powershell "Get-Service kubeproxy"
      done
    displayName: Restart Kubeproxy on Windows nodes
    retryCountOnTaskFailure: 3
- ${{ else }}:
  - info: Kube proxy restart action not available for Linux.
